inherit_from: .rubocop_todo.yml

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/CaseIndentation:
  EnforcedStyle: end

Style/DoubleNegation:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - Appraisals
    - '**/*_spec.rb'
    - '**/*.rake'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
