name: rubocop

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    strategy:
      matrix:
        gemfile: [ rails.5.2.activerecord ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ~/repo    
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      working_directory: ~/repo
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile    
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 
      
        run: ruby -v
      
      - name: Ruby gem cache
        id: gem-cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: dependencies-{{ checksum ".ruby.version" }}-{{ checksum ".Gemfile.lock.path" }}
          restore-keys: |
            dependencies-{{ checksum ".ruby.version" }}-

      - name: install dependencies
        run: bundle install --jobs=4 --retry=3 --path vendor/bundle --binstubs=/usr/local/bundle/bin

      - name: run rubocop
        run: bundle exec rubocop --format simple


# .github/workflows/rubocop.yml

name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x # Replace with your ruby version
    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





