name: rubocop

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v2

      run: bundle install
      run: aaa
      
commands:
  aaa:
    description: Test rspec in current ruby
    steps:
      - run: rubocop    
